server:
  port: 8082

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/account_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

jwt:
  secret: 50caab1114b4d2550f2713a933d9c58e2348f88e426a9e0cf8e954924b64f862